


# // LOCALHOST
### Get all authors
GET http://localhost:8080/author HTTP/1.1

###
GET  http://localhost:8080/book HTTP/1.1




// PRODUCTION Deploy
###
GET https://cse341-project2-lessons05-08.onrender.com/book 


###
GET https://cse341-project2-lessons05-08.onrender.com/author 




###
POST https://cse341-project2-lessons05-08.onrender.com/book HTTP/1.1
content-type: application/json

{
  "title": "Romeo and Juliet",
  "author": "William Shakespeare",
  "genre": "Tragedy",
  "publicationYear": 1597,
  "isbn": "9780743477116",
  "copiesAvailable": 5,
  "description": "Romeo and Juliet is a tragedy written by William Shakespeare early in his career about two young star-crossed lovers whose deaths ultimately reconcile their feuding families."
}

###
PUT https://cse341-project2-lessons05-08.onrender.com/book/65c4046c19d4a135b743dd04 HTTP/1.1
content-type: application/json

{
 "title": "Hamlet",
  "author": "William Shakespeare",
  "genre": "Tragedy",
  "publicationYear": 1603,
  "isbn": "9780141012278",
  "copiesAvailable": 10,
  "description": "Hamlet, Prince of Denmark, seeks revenge against his uncle, who has murdered Hamlet's father."
}

###
DELETE https://cse341-project2-lessons05-08.onrender.com/book/65c4112b815ee3e6197cf876




###
GET https://cse341-project2-lessons05-08.onrender.com/author
###
POST https://cse341-project2-lessons05-08.onrender.com/author HTTP/1.1
content-type: application/json

{
 "name": "William Shakespeare",
  "birthDate": "1564-04-23",
  "nationality": "English",
  "biography": "William Shakespeare was an English playwright...",
  "website": "https://www.shakespeare.org.uk/",
  "booksWritten": ["Hamlet", "Romeo and Juliet", "Macbeth"],
  "awards": ["None (considered one of the greatest playwrights in English literature)"]
}

###
PUT https://cse341-project2-lessons05-08.onrender.com/author/65c3e51613d6a7c025894bd8 HTTP/1.1
content-type: application/json

{
"awards": "Not applicable"
}

###
DELETE https://cse341-project2-lessons05-08.onrender.com/author/65c3e51613d6a7c025894bd8 HTTP/1.1